### ISSUE TITLE
how to change quality

### ISSUE THREAD

**Issue by thaynos** [ZReC/AnimePaheExtractor#2]
what it says in title

**Comment by ZReC** [comment]
I never finished that feature (so far), sorry. You could change it manually meanwhile (it's hardcoded)

**Comment by thaynos** [comment]
how do i change it to 720p?

**Comment by ZReC** [comment]
I'm closing the issue because there's a [new version](../../AnimePaheXtractor/) of this app with additional features and enhancements including this one. You may want to check it out if you're still around. Thanks for asking!
